services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@f1-interactive-db:5432/${DATABASE_NAME:-f1interactive}
      - DATABASE_TYPE=postgresql
      - APP_SECRET=${UMAMI_SECRET:-ReplaceThisWithARandomString}
      - BASE_PATH=/umami
    ports:
      - "3000:3000"
    networks:
      - f1interactive-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
    depends_on:
      - db

networks:
  f1interactive-net:
    external: true
