app:
  version: "@project.version@"
server:
  port: 8080
  servlet:
    contextPath: /f1interactive
  ssl:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: default
  jackson:
    default-property-inclusion: non_null
datasource:
  url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  driverClassName: org.postgresql.Driver
  defaultSchema: ${DATABASE_SCHEMA}
  maxPoolSize: ${MAX_POOL_SIZE:3}
  hibernate:
    hbm2ddl.method: none
    show_sql: false
    format_sql: false
    dialect: org.hibernate.dialect.PostgreSQLDialect
rest:
  cors:
    allowedOriginPatterns: ${ALLOWED_ORIGIN_PATTERNS}
---
spring:
  config:
    activate:
      on-profile: local
  jackson:
    default-property-inclusion: non_null
datasource:
  url: jdbc:postgresql://localhost:5432/F1INTERACTIVE
  username: f1interactive
  password: f1interactive
  driverClassName: org.postgresql.Driver
  defaultSchema: F1INTERACTIVE
  maxPoolSize: 3
  hibernate:
    #hbm2ddl.method: update
    hbm2ddl.method: none
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
rest:
  cors:
    allowedOriginPatterns: "http://localhost:4200"