\connect __DATABASE_NAME__

-- Minimal default-privilege rules for the runtime Postgres user
ALTER DEFAULT PRIVILEGES IN SCHEMA __DATABASE_SCHEMA__ GRANT ALL ON TABLES TO __POSTGRES_USER__;
ALTER DEFAULT PRIVILEGES IN SCHEMA __DATABASE_SCHEMA__ GRANT USAGE, SELECT ON SEQUENCES TO __POSTGRES_USER__;
