-- Ensure the role has required privileges on database, schema, tables and sequences
GRANT CONNECT ON DATABASE __DATABASE_NAME__ TO __DATABASE_USER__;
\connect __DATABASE_NAME__
GRANT USAGE ON SCHEMA __DATABASE_SCHEMA__ TO __DATABASE_USER__;
GRANT ALL PRIVILEGES ON SCHEMA __DATABASE_SCHEMA__ TO __DATABASE_USER__;
GRANT ALL ON ALL TABLES IN SCHEMA __DATABASE_SCHEMA__ TO __DATABASE_USER__;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA __DATABASE_SCHEMA__ TO __DATABASE_USER__;

-- Future objects in the schema should also grant to the user
ALTER DEFAULT PRIVILEGES IN SCHEMA __DATABASE_SCHEMA__ GRANT ALL ON TABLES TO __DATABASE_USER__;
ALTER DEFAULT PRIVILEGES IN SCHEMA __DATABASE_SCHEMA__ GRANT USAGE, SELECT ON SEQUENCES TO __DATABASE_USER__;
